language: node_js
node_js:
  - '12.13'

stages:
  - compile
  - test
  - lint
  - name: deploy
    if: branch = master


install: npm

jobs:
  include:
    - stage: compile
      name: "Compile"            # names the first Tests stage job
      script: npm build
    - stage: lint
      name: "Eslint"            # names the first Tests stage job
      script: npm lint
    - stage: test
      name: "Unit Tests"            # names the first Tests stage job
      script: npm test
    - stage: deploy
      name: "Deploy to npm"
      provider: npm
        email: reporting-dev@perfectomobile.com
        on:
          branch: master
        tag: latest
        before_deploy:
          - npm version patch
          - git push origin master --tag
        api_key:
          # Use the following row to encrypt npm auth token
          # travis encrypt YOUR_NPM_AUTH_TOKEN --add deploy.api_key
          secure: r4Frt5aedYAVhvOq2izHbY2A5JM7MQprrDDRTU31n4vuaVgiINSu4aFt/arWumLell6GlEX8Kln7e9RhqZajev9uRkNUAZAi8/o1G5YihFg2p1tlCDHkslLRPWDmKafngBYPM2xwNbK+CmRIjNEi6/HEK1flsikVsApFvEq+a+6GVDWhtUOX1q9qN83A5f08hohgMOnRCUZSW9lpHfKyFx0G1p8QW04pl+Rb4NQHO11AYlygTl2vdKhI2ooM8gBkvFVR7LpLZRglBBUmFaqOjoOymSV0GgWrdoAgrYTb8UWkfrADD7TzSIZ2iHYw3dIWyrOLhkrdhVhEEHxE9y0f0gS58SkMG6E7PKJK9YiNfDzzyE96UwIJOMS/9FDYgKAPvUfnii8YfDtnUrWzWpC9bwtlZ/veEiYBR2KdVqvjvj+H55BLE8tjSRIo9ez9PthjrJC6XNjN2c2tASUdusXwJHNDxi5N+3A0ivUvCU5b1Cos2Ri82PMUQRoeEqV6vI3vd/qnJOx3FwIrq6zIVw/0tKc5nf2CG/8e+KrqXcUutv+DY4InTvU3wxdNowGr/3cVlKjkpzgOTfwOiLvQMjEK7llsVA9yu/wxFwDP79Xo2+tjmc/LDWlzivq5Nb+IXiD1sWx360bMPSn04tqOxsdKTDflhlU/CwVQdX62ZpHmlG8=

